# Generated by Django 5.1.7 on 2025-04-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_coupon_orders_final_price_orders_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='valid_to',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='final_price',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.FloatField(help_text='Enter percentage value (e.g. 10 for 10%)'),
        ),
    ]
