# Generated by Django 5.1.7 on 2025-04-13 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_remove_coupon_valid_from_remove_coupon_valid_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecom.coupon'),
        ),
    ]
